### ISSUE TITLE
I spread hate ~ Wizz

### ISSUE THREAD

**Issue by Wizz1337** [xtekky/TikTok-xchecker#1]
first dont skid 
twice use brain

**Comment by xtekky** [comment]
skid? from who? myself? ... stop just randomly telling people they are skids : (

**Comment by Wizz1337** [comment]
bruh idiot you cant make your own readme
and dont say its not skidding cuz you literally put your credits in

**Comment by Wizz1337** [comment]
and i just see that you skidded some github repo -_-

**Comment by xtekky** [comment]
I normally leave creds and don't just say I skidded some random repo, because **I didnt ...**, I just decided to now embed descriptions in code blocks and make a centered title at the beginning like you did, I think that there is no skidding...

**Comment by Wizz1337** [comment]
where credits ?
![image](https://user-images.githubusercontent.com/70026238/171479843-8de5fea3-7303-49a2-9024-81780b499cdd.png)

**Comment by Wizz1337** [comment]
> I normally leave creds and don't just say I skidded some random repo, because **I didnt ...**, I just decided to now embed descriptions in code blocks and make a centered title at the beginning like you did, I think that there is no skidding...

you can say that you just copy and paste

**Comment by xtekky** [comment]
**OMG**, this is not in relation to this repo, neither I claimed these my own, it was just a research repo where I pasted and shared stuff I found in relation to that. You are totally in the wrong, the discussion is finished here. This is abusive behaviour... , you are telling me about being a good dev when you aren't even a good person :/
